export const cities = [
  { state: "Uttar Pradesh", city: "Lucknow" },
  { state: "Uttar Pradesh", city: "Varanasi" },
  { state: "Uttar Pradesh", city: "Agra" },
  { state: "Uttar Pradesh", city: "Allahabad" },
  { state: "Uttar Pradesh", city: "Kanpur" },
  { state: "Uttar Pradesh", city: "Mathura" },
  { state: "Uttar Pradesh", city: "Vrindavan" },
  { state: "Uttar Pradesh", city: "Ayodhya" },
  { state: "Uttar Pradesh", city: "Jhansi" },
  { state: "Uttar Pradesh", city: "Meerut" },

  { state: "Kerala", city: "Kochi" },
  { state: "Kerala", city: "Thiruvananthapuram" },
  { state: "Kerala", city: "Kozhikode" },
  { state: "Kerala", city: "Thrissur" },
  { state: "Kerala", city: "Kannur" },
  { state: "Kerala", city: "Kollam" },
  { state: "Kerala", city: "Alappuzha" },
  { state: "Kerala", city: "Kottayam" },
  { state: "Kerala", city: "Palakkad" },
  { state: "Kerala", city: "Malappuram" },

  { state: "Maharashtra", city: "Mumbai" },
  { state: "Maharashtra", city: "Pune" },
  { state: "Maharashtra", city: "Nagpur" },
  { state: "Maharashtra", city: "Aurangabad" },
  { state: "Maharashtra", city: "Nashik" },
  { state: "Maharashtra", city: "Thane" },
  { state: "Maharashtra", city: "Navi Mumbai" },
  { state: "Maharashtra", city: "Solapur" },
  { state: "Maharashtra", city: "Kolhapur" },
  { state: "Maharashtra", city: "Amravati" },

  { state: "Tamil Nadu", city: "Chennai" },
  { state: "Tamil Nadu", city: "Madurai" },
  { state: "Tamil Nadu", city: "Coimbatore" },
  { state: "Tamil Nadu", city: "Tiruchirappalli" },
  { state: "Tamil Nadu", city: "Tiruppur" },
  { state: "Tamil Nadu", city: "Salem" },
  { state: "Tamil Nadu", city: "Tirunelveli" },
  { state: "Tamil Nadu", city: "Erode" },
  { state: "Tamil Nadu", city: "Vellore" },
  { state: "Tamil Nadu", city: "Dindigul" },

  { state: "Gujarat", city: "Ahmedabad" },
  { state: "Gujarat", city: "Surat" },
  { state: "Gujarat", city: "Vadodara" },
  { state: "Gujarat", city: "Rajkot" },
  { state: "Gujarat", city: "Bhavnagar" },
  { state: "Gujarat", city: "Jamnagar" },
  { state: "Gujarat", city: "Junagadh" },
  { state: "Gujarat", city: "Gandhinagar" },
  { state: "Gujarat", city: "Bhuj" },
  { state: "Gujarat", city: "Porbandar" },

  { state: "Madhya Pradesh", city: "Bhopal" },
  { state: "Madhya Pradesh", city: "Indore" },
  { state: "Madhya Pradesh", city: "Jabalpur" },
  { state: "Madhya Pradesh", city: "Gwalior" },
  { state: "Madhya Pradesh", city: "Ujjain" },
  { state: "Madhya Pradesh", city: "Rewa" },
  { state: "Madhya Pradesh", city: "Satna" },
  { state: "Madhya Pradesh", city: "Sagar" },
  { state: "Madhya Pradesh", city: "Murwara" },
  { state: "Madhya Pradesh", city: "Burhanpur" },

  { state: "Jharkhand", city: "Ranchi" },
  { state: "Jharkhand", city: "Jamshedpur" },
  { state: "Jharkhand", city: "Dhanbad" },
  { state: "Jharkhand", city: "Bokaro Steel City" },
  { state: "Jharkhand", city: "Hazaribagh" },
  { state: "Jharkhand", city: "Giridih" },
  { state: "Jharkhand", city: "Deoghar" },
  { state: "Jharkhand", city: "Phusro" },
  { state: "Jharkhand", city: "Ramgarh" },
  { state: "Jharkhand", city: "Medininagar" },

  { state: "Karnataka", city: "Bengaluru" },
  { state: "Karnataka", city: "Mysuru" },
  { state: "Karnataka", city: "Mangaluru" },
  { state: "Karnataka", city: "Hubballi-Dharwad" },
  { state: "Karnataka", city: "Belagavi" },
  { state: "Karnataka", city: "Kalaburagi" },
  { state: "Karnataka", city: "Shivamogga" },
  { state: "Karnataka", city: "Tumakuru" },
  { state: "Karnataka", city: "Raipur" },
  { state: "Karnataka", city: "Vijayapura" },

  { state: "Punjab", city: "Amritsar" },
  { state: "Punjab", city: "Ludhiana" },
  { state: "Punjab", city: "Jalandhar" },
  { state: "Punjab", city: "Patiala" },
  { state: "Punjab", city: "Bathinda" },
  { state: "Punjab", city: "Mohali" },
  { state: "Punjab", city: "Pathankot" },
  { state: "Punjab", city: "Hoshiarpur" },
  { state: "Punjab", city: "Moga" },
  { state: "Punjab", city: "Firozpur" },

  { state: "Rajasthan", city: "Jaipur" },
  { state: "Rajasthan", city: "Jodhpur" },
  { state: "Rajasthan", city: "Kota" },
  { state: "Rajasthan", city: "Bikaner" },
  { state: "Rajasthan", city: "Udaipur" },
  { state: "Rajasthan", city: "Ajmer" },
  { state: "Rajasthan", city: "Alwar" },
  { state: "Rajasthan", city: "Bharatpur" },
  { state: "Rajasthan", city: "Sikar" },
  { state: "Rajasthan", city: "Pali" },

  { state: "West Bengal", city: "Kolkata" },
  { state: "West Bengal", city: "Asansol" },
  { state: "West Bengal", city: "Siliguri" },
  { state: "West Bengal", city: "Durgapur" },
  { state: "West Bengal", city: "Baharampur" },
  { state: "West Bengal", city: "Raiganj" },
  { state: "West Bengal", city: "Kharagpur" },
  { state: "West Bengal", city: "Sambalpur" },
  { state: "West Bengal", city: "Malda" },
  { state: "West Bengal", city: "Balurghat" },

  { state: "Andhra Pradesh", city: "Visakhapatnam" },
  { state: "Andhra Pradesh", city: "Vijayawada" },
  { state: "Andhra Pradesh", city: "Tirupati" },
  { state: "Andhra Pradesh", city: "Kakinada" },
  { state: "Andhra Pradesh", city: "Nellore" },
  { state: "Andhra Pradesh", city: "Rajahmundry" },
  { state: "Andhra Pradesh", city: "Kurnool" },
  { state: "Andhra Pradesh", city: "Anantapur" },
  { state: "Andhra Pradesh", city: "Guntur" },
  { state: "Andhra Pradesh", city: "Kadapa" },

  { state: "Chhattisgarh", city: "Raipur" },
  { state: "Chhattisgarh", city: "Bhilai Nagar" },
  { state: "Chhattisgarh", city: "Durg" },
  { state: "Chhattisgarh", city: "Bilaspur" },
  { state: "Chhattisgarh", city: "Raigarh" },
  { state: "Chhattisgarh", city: "Korba" },
  { state: "Chhattisgarh", city: "Rajnandgaon" },
  { state: "Chhattisgarh", city: "Jagdalpur" },
  { state: "Chhattisgarh", city: "Ambikapur" },
  { state: "Chhattisgarh", city: "Dhamtari" },

  { state: "Telangana", city: "Hyderabad" },
  { state: "Telangana", city: "Warangal" },
  { state: "Telangana", city: "Nizamabad" },
  { state: "Telangana", city: "Karimnagar" },
  { state: "Telangana", city: "Ramagundam" },
  { state: "Telangana", city: "Khammam" },
  { state: "Telangana", city: "Mahbubnagar" },
  { state: "Telangana", city: "Suryapet" },
  { state: "Telangana", city: "Adilabad" },
  { state: "Telangana", city: "Mancherial" },

  { state: "Assam", city: "Guwahati" },
  { state: "Assam", city: "Silchar" },
  { state: "Assam", city: "Dibrugarh" },
  { state: "Assam", city: "Tezpur" },
  { state: "Assam", city: "Jorhat" },
  { state: "Assam", city: "Nagaon" },
  { state: "Assam", city: "Dhubri" },
  { state: "Assam", city: "Bongaigaon" },
  { state: "Assam", city: "Nalbari" },
  { state: "Assam", city: "Karimganj" },

  { state: "Bihar", city: "Patna" },
  { state: "Bihar", city: "Gaya" },
  { state: "Bihar", city: "Bhagalpur" },
  { state: "Bihar", city: "Muzaffarpur" },
  { state: "Bihar", city: "Darbhanga" },
  { state: "Bihar", city: "Purnea" },
  { state: "Bihar", city: "Begusarai" },
  { state: "Bihar", city: "Munger" },
  { state: "Bihar", city: "Saharsa" },
  { state: "Bihar", city: "Biharsharif" },

  { state: "Odisha", city: "Bhubaneswar" },
  { state: "Odisha", city: "Cuttack" },
  { state: "Odisha", city: "Rourkela" },
  { state: "Odisha", city: "Berhampur" },
  { state: "Odisha", city: "Sambalpur" },
  { state: "Odisha", city: "Puri" },
  { state: "Odisha", city: "Balasore" },
  { state: "Odisha", city: "Brahmapur" },
  { state: "Odisha", city: "Baripada" },
  { state: "Odisha", city: "Rourkela Steel City" },

  { state: "Uttarakhand", city: "Dehradun" },
  { state: "Uttarakhand", city: "Haridwar" },
  { state: "Uttarakhand", city: "Haldwani-cum-Kathgodam" },
  { state: "Uttarakhand", city: "Roorkee" },
  { state: "Uttarakhand", city: "Rishikesh" },
  { state: "Uttarakhand", city: "Kashipur" },
  { state: "Uttarakhand", city: "Rudrapur" },
  { state: "Uttarakhand", city: "Nainital" },
  { state: "Uttarakhand", city: "Srinagar" },
  { state: "Uttarakhand", city: "Mussoorie" },

  { state: "Chandigarh", city: "Chandigarh" },

  { state: "Delhi", city: "New Delhi" },

  { state: "Jammu & Kashmir", city: "Srinagar" },
  { state: "Jammu & Kashmir", city: "Jammu" },
  { state: "Jammu & Kashmir", city: "Baramulla" },
  { state: "Jammu & Kashmir", city: "Anantnag" },
  { state: "Jammu & Kashmir", city: "Sopore" },
  { state: "Jammu & Kashmir", city: "Rajauri" },
  { state: "Jammu & Kashmir", city: "Kathua" },
  { state: "Jammu & Kashmir", city: "Udhampur" },
  { state: "Jammu & Kashmir", city: "Handwara" },
  { state: "Jammu & Kashmir", city: "Kupwara" },
];
